[package]
name = "darkroom"
version = "0.5.0-a"
description = "A contract testing tool built in Rust"
authors = ["Matthew Planchard <msplanchard@gmail.com>", "Mikhail Katychev <mkatych@gmail.com>"]
edition = "2018"
license = "GPL-3.0"
readme = "README.md"

documentation = "https://docs.rs/crate/darkroom/"
homepage = "https://crates.io/crates/darkroom"
repository = "https://github.com/Bestowinc/darkroom/"

[[bin]]
name = "dark"
path = "src/main.rs"

[workspace]
members = [
  "filmreel"
]

[dependencies]
anyhow = "1.0"
argh = "0.1"
colored = "1.9"
colored-diff = "0.2"
colored_json = "2"
filmreel = { version = "0.3", path = "filmreel" }
http = "0.2"
lazy_static = "1.4"
log = { version = "0.4", features = ["std"] }
prettytable-rs = "^0.8"
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.44"
url = "2.1"
which = "3.1"
chrono = "0.4"

[dev-dependencies]
rstest = "0.5"
