[package]
name = "darkroom"
version = "0.1.0"
description = "A contract testing tool built in Rust"
authors = ["Matthew Planchard <msplanchard@gmail.com>", "Mikhail Katychev <mkatych@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

documentation = "https://docs.rs/crate/darkroom/"
homepage = "https://crates.io/crates/darkroom"
repository = "https://github.com/Bestowinc/darkroom/"

[[bin]]
name = "dark"
path = "src/main.rs"

[workspace]
members = [
  "filmreel"
]

[dependencies]
argh = "0.1"
colored = "1.9"
filmreel = { version = "0.1.0", path = "filmreel" }
serde = { version = "1.0.104", features = ["derive"] }
serde_yaml = "0.8"
